# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78387c257b56cf6251d3993f1567e6c0940807c2acd7a1a96eebb73755263108f5c1c9d5f3fb971be73318bf11ef74627ddeb73d6590f1db77fcf80c4e23355a

test:
  secret_key_base: d6cfb932b2fb8c1ac9608f27821093ebb471e51ad287a80b782a9fc5adc58d61109b508a63e87966e3627e0269fc5602eccf423fa86c5bd9df48fc093920a8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
